### ISSUE TITLE
Connect to database

### ISSUE THREAD

**Issue by vanheck** [vanheck/HeckBlog#2]
Use the postgres database.

**Comment by vanheck** [comment]
If I use volume in docker for postgres image in docker-compose.yml:

```yaml
services:
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: blogdmin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: heckblog
        volumes:
            - ./dbdata:/var/lib/postgresql/data

    web:
        build: .
        command: >
            gunicorn -b 0.0.0.0:8000
                --access-logfile -
                --reload
                "heckblog.wsgi:application"
        volumes:
            - ./heckblog:/heckblog
        depends_on:
            - db
        environment: 
            IN_DOCKER: 1
        ports:
            - "80:8000"
```

it end with error:

```cmd
FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
HINT:  The server must be started by the user that owns the data directory.
```

**Comment by vanheck** [comment]
It is windows problem. Here is describe the problem:
https://forums.docker.com/t/trying-to-get-postgres-to-work-on-persistent-windows-mount-two-issues/12456/5

I've fix it by creating docker volume:

```yaml
version: '2'

services:
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: blogdmin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: heckblog
            PGDATA: /tmp
        volumes:
            - postgres_data:/var/lib/postgresql/data

    web:
        build: .
        command: >
            gunicorn -b 0.0.0.0:8000
                --access-logfile -
                --reload
                "heckblog.wsgi:application"
        volumes:
            - ./heckblog:/heckblog
        depends_on:
            - db
        environment: 
            IN_DOCKER: 1
        ports:
            - "80:8000"

volumes:
    postgres_data:
```
